name: "Bot notify ronin by last price"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  notify-ronin-by-last-price:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: "false"
    - run: ./jobs/ronin-notify-by-last-price.sh
    env:
      TELEGRAM_CHAT_ID: '-1001318480244,-649357836,-999154067' # be, sm-sre, bot
      NOTIFY_PERCENT: '5.0'
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
      LAST_PRICE_KEY: 'ronin:price:bot:last'