name: "Bot notify ronin pricing at time"
on:
  schedule:
  - cron: "0 1,8,15 * * *"

jobs:
  notify-ronin-at-time-gfbaby:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shogo82148/actions-setup-redis@v1
      with:
        auto-start: "false"
    - run: ./jobs/ronin-notify.sh
    env:
      TELEGRAM_CHAT_ID: '-1001318480244,-649357836,-999154067,-1001913309928' # be, sm-sre, bot
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      REDIS_ADDR: ${{ secrets.REDIS_ADDR }}
      LAST_PRICE_KEY: 'ronin:price:bot:last'
